---
version: 2
checks:
  identical-code:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
exclude_patterns:
  - "src/*.js"
  - "src/**/*.js.snap"
  - "src/**/*.test.js"
plugins:
  eslint:
    enabled: false
  stylelint:
    enabled: false
