exclude:
  - 'node_modules/**/*.*'
linters:
  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  ElsePlacement:
    enabled: true
    style: new_line

  ImportPath:
    enabled: false

  SelectorFormat:
    convention: hyphenated_BEM

  SpaceAfterComma:
    enabled: true
    style: at_least_one_space

  SpaceAfterPropertyColon:
    enabled: true
    style: aligned

  SpaceAfterVariableColon:
    enabled: false
    style: at_least_one_space
